### ISSUE TITLE
Add support for themes with style.css in a subdirectory

### ISSUE THREAD

**Issue by atanas-angelov-dev** [cedaro/node-wp-i18n#16]
Crude example of what my setup looks like:

```
wp-content/themes/my-theme
├── includes/
│   └── helpers.php
├── languages/
│   └── my-theme.pot
├── subdir/
│   └── style.css
└── package.json
```

As you can see, my `style.css` is in a subdirectory (supported by WordPress) which means that I can't run `wpi18n` in the root theme directory as it fails to find it.
I tried changing the working directory when running wpi18n (e.g. `(cd subdir && wpi18n ...)`) however this has a couple of issues:

1. All paths in the `.pot` file will be relative to `subdir/` but since `languages/` is outside of it, the paths will be incorrect.
1. Any files with translation function calls outside of `subdir/` like `includes/helpers.php` will not get indexed.

Let me know if I'm missing anything or support for this use case is indeed not implemented.

**Comment by bradyvercher** [comment]
I'm familiar with putting `style.css` in a subdirectory, but I'm pretty sure WordPress won't recognize that as a valid theme unless you're using some sort of custom loading process. Where are you saving `index.php` and `functions.php`? 

It *might* be possible to stick with that layout and still use `wpi18n`, but you'll probably need to manually provide as many of the [arguments](https://github.com/cedaro/node-wp-i18n/blob/51c676f7b26ab2c9232ea1edac25222a51833fd1/docs/cli.txt#L13-L17) as possible.

**Comment by atanas-angelov-dev** [comment]
It works fine - WordPress finds everything as long as functions.php, index.php, header.php etc. are in the same directory as style.css (style.css's directory is considered the theme template_dir and is allowed to be up to 1 level nested inside the theme root)

**Comment by bradyvercher** [comment]
Right, but as far as WordPress is concerned, the subdirectory is the theme directory, so it doesn't really consider `/includes`, `/languages`, or `package.json` to be a part of the theme. They just happen to be located one level up from the theme directory, but they could be anywhere on the filesystem.

There could also potentially be multiple themes in the `my-theme` directory, so most of the arguments really need to be supplied anyway if you're running `wpi18n` from that directory instead of the actual theme directory.

Did you try manually providing those arguments to see if it worked?

**Comment by atanas-angelov-dev** [comment]
Passed everything I could (--main-file, --domain-path etc.),  but it fails because it tries to locate style.css in the root directory unless I run it from that directory which causes the issues I mentioned in the OP.

**Comment by bradyvercher** [comment]
Dang! I took a closer look and the core PHP tools aren't really set up to handle that use case. They expect the command to be called from the same directory where `style.css` is located.

I'll leave this open in case anyone wants to try to add support or if I find time in the future, otherwise you might try the new [i18n command in WP-CLI](https://developer.wordpress.org/cli/commands/i18n/make-pot/).

**Comment by atanas-angelov-dev** [comment]
I'll give adding support a try next time I have some free time - thanks for the quick responses :)

**Comment by atanas-angelov-dev** [comment]
Just submitted #17 which addresses my issue - let me know what you think.

**Comment by bradyvercher** [comment]
This should be good to go with #17. Thanks again @atanas-angelov-dev.
