### ISSUE TITLE
Scan JS files

### ISSUE THREAD

**Issue by nathanrice** [cedaro/node-wp-i18n#19]
WordPress now allows for translatable strings in JS files with Gutenberg blocks.

They've made it so that the usage is almost identical, assuming you follow the same patterns they do in their source.

Is it possible to allow node-wp-i18n to scan the JS files in a theme/plugin folder for translatable strings? Obviously, we'd need to do so for both `addtextdomain` and `makepot`.

**Comment by bradyvercher** [comment]
It's been awhile since I've checked to see how Gutenberg handles i18n, so I'm not super familiar with how it works at the moment.

From what I gathered, [a Babel plugin](https://github.com/WordPress/gutenberg/tree/master/packages/babel-plugin-makepot) is used to generate a POT file containing strings used in JavaScript files. That POT file could then either be converted into a PHP file that node-wp-i18n could scan, or it could be merged with the POT file generated by node-wp-i18n.

I'm guessing things may have changed since then, but I haven't had a chance to dig in. Do you know what the current process looks like for core?

**Comment by nathanrice** [comment]
Yeah, I believe that's the current workflow. There's some [more info here](https://make.wordpress.org/core/2018/11/09/5-0-javascript-language-packs-are-here-%F0%9F%8E%89/).

This doesn't seem ideal to me.

For starters, there is no way to run the `node-wp-i18n` command for `addtextdomain` on JS files. This is really useful for catching those instances where you forget to add the textdomain to a string.

Additionally, the POT file that `node-wp-i18n` would be incomplete, given that it's not pulling translatable strings from the JS files.

It looks like this package [actively limits](https://github.com/cedaro/node-wp-i18n/blob/develop/bin/php/extract.php#L33-L36) the scanning to PHP files, regardless of glob pattern (**/*.js doesn't work).

Ideally we wouldn't be passing responsibility for ultimately creating an accurate POT file back and forth between tools. If the intention is to not add JS file support for the bundled `node-wp-i18n` tasks, I'd like to know so I can look into other options.

**Comment by nathanrice** [comment]
>It's been awhile since I've checked to see how Gutenberg handles i18n, so I'm not super familiar with how it works at the moment.

FWIW, it's literally the exact same pattern as in PHP files.

```JS
import { __, _x } from '@wordpress/i18n';

var someVar = __( 'Translatable string', 'textdomain' );
var anotherVar = _x( 'Translatable string', 'textdomain' );
```

**Comment by bradyvercher** [comment]
> Ideally we wouldn't be passing responsibility for ultimately creating an accurate POT file back and forth between tools.

I agree it's not ideal, but support for loading translations for themes and plugins wasn't (isn't?) final, so determining the ideal workflow for themes and plugins wasn't possible.

> FWIW, it's literally the exact same pattern as in PHP files.

I've used that myself, but there wasn't a workflow for loading translations until recently, which is what I wasn't familiar with.

> It looks like this package actively limits the scanning to PHP files, regardless of glob pattern (**/*.js doesn't work).

The file you linked to is a forked version of core's i18n tools and was built specifically for PHP. It works by reading the contents of a file, [tokenizing it](http://php.net/token_get_all), then looping through each token to determine if it's an i18n function. It wouldn't work for JS even if the `.js` extension were enabled.

Adding support for JS files would require bundling a different package to handle `.js` files and it would also need to be able to handle JSX syntax.

Since the output of the PHP tools is a POT file and a different package would be handling the JS files, the resulting strings would need to be merged. It would be nice to have all of that happen internally so multiple routines/tasks wouldn't need to be configured.

> If the intention is to not add JS file support for the bundled node-wp-i18n tasks, I'd like to know so I can look into other options.

It would be my preference to add support for JS if possible, but I don't have the resources to tackle it myself at the moment. Aside from the Babel plugin I mentioned, the i18n command in WP-CLI is an option you might look into since it's an official WP.org project.
